### ISSUE TITLE
model was not saved！ current best Avg，Dice：0.0 current Avg Dice：nan 

### ISSUE THREAD

**Issue by aixiaobaikkk** [MASILab/3DUX-Net#29]
Hi , thank you very much for your great work，I have meet some trouble  when I train the amos dataset，it just shows ：

l 21/240 [01:17<11:29，3.15s/it]  Model Was Not Saved ! Current Best Avg. Dice: 0.0 Current Avg.Dice: nan

I wander why it happened，how to solove it

**Comment by leeh43** [comment]
Hi, thank you for your interest towards our work! Just want to have more information, have you changed any lines of code?

**Comment by SanmAIGO** [comment]
@leeh43 Hello, I also had this problem with the AMOS2022 dataset. I modified：
RandCropByPosNegLabeld(
                    keys=["image", "label"],
                    label_key="label",
                    spatial_size=(96, 96, 96),
                    pos=1,
                    neg=1,
                    num_samples=crop_samples,
                    image_key="image",
                    image_threshold=0,
                    allow_smaller=True    #changed 
                ),
The above modification is to avoid：
ValueError: The size of the proposed random crop ROI is larger than the image size.

这是为什么呢？

**Comment by SanmAIGO** [comment]
@leeh43 Hello, I also had this problem with the AMOS2022 dataset. I modified：
RandCropByPosNegLabeld(
keys=["image", "label"],
label_key="label",
spatial_size=(96, 96, 96),
pos=1,
neg=1,
num_samples=crop_samples,
image_key="image",
image_threshold=0,
allow_smaller=True #changed
),
The above modification is to avoid：
ValueError: The size of the proposed random crop ROI is larger than the image size.

That's why, and what can I do to replicate your experiment on AMOS2022. ValueError Error log I provided in this issue#32 
Looking forward to your reply.
Sanm

**Comment by leeh43** [comment]
Hi @aixiaobaikkk, I have double checked the main_finetune.py code for finetuning and it didn't happen your error with the following screenshot:
<img width="1440" alt="image" src="https://github.com/MASILab/3DUX-Net/assets/54121206/1ce4c217-c953-4014-b1e7-c8487ec7babc">

Just want to clarify the AMOS experiment in our paper is only for **CT organ segmentation**, please refer the dataset json file for task 1 in AMOS challenge.


Hi @SanmAIGO, please keep the original code for the data transform and I believed the code is doing good with the above screenshot.

**Comment by aixiaobaikkk** [comment]
@leeh43 Thanks for your reply ，I was too busy studying during this time to continue working on the project, after which I would check my code and continue learning this great project
