### ISSUE TITLE
About the task being killed using test_seg.py memory overflow on the AMOS2022 dataset

### ISSUE THREAD

**Issue by SanmAIGO** [MASILab/3DUX-Net#33]
Hi author, when I tested the AMOS2022 data set again, test_seg.py caused a memory overflow and the task was killed. I didn't change any code, and I didn't change AMOS2022 and was killed around 166th inference amos_467.nii.gz. My computer has 32GB of RAM. Why is that? If I want to use test_seg.py how much RAM do I have or how do I do it?

**Comment by SanmAIGO** [comment]
I noticed that only 200 cases were used for the experiments of AMOS2022 in the appendix of your paper, but I used all the data in AMOS. Can you disclose your data split? My email is [xiaosenforai@gmail.com](mailto:xiaosenforai@gmail.com). Thank you for sharing.

**Comment by SanmAIGO** [comment]
Could you please disclose the data split for AMOS2022, FLERA2021 and FeTA2021 datasets? Thank you very much! Wish you all the best in your works.

**Comment by leeh43** [comment]
Hi, for testing, please reduce the overlapping ratio from 0.7 to 0.5 or the number of patches from 4 to 2 if the testing python script got killed. The reason got killed is because of the sliding window inference in MONAI need a lot of amount CPU memory.

Furthermore, in my experiments, I only use the CTs in AMOS 2022, which consists of  200 cases. I will upload the FeTA split and AMOS split before the end of next Friday, as I am not in US currently. I have put the FLARE split in the GitHub and feel free to take a look!

**Comment by SanmAIGO** [comment]
@leeh43 
Thank you for your busy reply. I wish you all the best and do more excellent work in the future.
Best regards.
Sanm

**Comment by SanmAIGO** [comment]
@leeh43 
Thank you for taking the time to respond amidst your busy schedule. I wish you all the best and hope that your work will become increasingly outstanding in the future.
Best regards.
Sanm
